version: '3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - chatbox_postgres:/var/lib/postgresql/data/
  web:
    build: .
    command: /code/run_production.sh
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FORWARD_PORT=3000
      - VIRTUAL_HOST=chatbox.docker-e9.ijs.si
      - LETSENCRYPT_HOST=chatbox.docker-e9.ijs.si
      - LETSENCRYPT_EMAIL=vh9691@student.uni-lj.si
    depends_on:
      - db

volumes:
  chatbox_postgres:
